### ISSUE TITLE
Demo or screenshots

### ISSUE THREAD

**Issue by manuelmeurer** [rajeevkannav/gutter#5]
I think a demo of gutter (Heroku would be simplest) or at least some screenshots in the readme would be very helpful for people to understand what it is and does! :smile:

**Comment by rajeevkannav** [comment]
@manuelmeurer  have you used it and is that works for your project ?

**Comment by manuelmeurer** [comment]
No, I just saw the link somewhere and landed on the Github page. But just based on the one line description and a few features I have no idea what gutter actually does and how it looks like.

**Comment by rajeevkannav** [comment]
@manuelmeurer  Give it a try that will be very helpful , if it works then I'll deploy it to heroku and update Read me with screenshot

**Comment by manuelmeurer** [comment]
I'm currently not looking for a dashboard, this was simply a friendly suggestion on making your project more approachable.
